"""由 scripts/generate_models.py 生成，请勿手工修改。"""

from pi.ai.types import Model

MODELS = [Model.model_validate(item) for item in [{'id': 'gpt-4o',
  'name': 'GPT-4o',
  'api': 'openai-chat-completions',
  'provider': 'openai',
  'base_url': 'https://api.openai.com/v1',
  'reasoning': False,
  'input': ['text', 'image'],
  'cost': {'input': 2.5, 'output': 10.0, 'cache_read': 0.0, 'cache_write': 0.0},
  'context_window': 128000,
  'max_tokens': 16384,
  'compat': {'developer_role': 'system',
             'supports_thinking': False,
             'thinking_format': 'interleaved',
             'supports_strict_tools': False,
             'supports_cache': False,
             'cache_type': 'ephemeral',
             'supports_session_affinity': False,
             'session_affinity_field': 'previous_response_id',
             'thinking_level_map': {},
             'supports_images': False,
             'supports_streaming_thinking': False,
             'requires_tool_choice': False,
             'reports_reasoning_tokens': False}},
 {'id': 'gpt-4o-mini',
  'name': 'GPT-4o mini',
  'api': 'openai-chat-completions',
  'provider': 'openai',
  'base_url': 'https://api.openai.com/v1',
  'reasoning': False,
  'input': ['text', 'image'],
  'cost': {'input': 0.15, 'output': 0.6, 'cache_read': 0.0, 'cache_write': 0.0},
  'context_window': 128000,
  'max_tokens': 16384,
  'compat': {'developer_role': 'system',
             'supports_thinking': False,
             'thinking_format': 'interleaved',
             'supports_strict_tools': False,
             'supports_cache': False,
             'cache_type': 'ephemeral',
             'supports_session_affinity': False,
             'session_affinity_field': 'previous_response_id',
             'thinking_level_map': {},
             'supports_images': False,
             'supports_streaming_thinking': False,
             'requires_tool_choice': False,
             'reports_reasoning_tokens': False}},
 {'id': 'claude-sonnet-4-20250514',
  'name': 'Claude Sonnet 4',
  'api': 'anthropic-messages',
  'provider': 'anthropic',
  'base_url': 'https://api.anthropic.com',
  'reasoning': True,
  'input': ['text', 'image'],
  'cost': {'input': 3.0, 'output': 15.0, 'cache_read': 0.0, 'cache_write': 0.0},
  'context_window': 200000,
  'max_tokens': 16384,
  'compat': {'developer_role': 'system',
             'supports_thinking': False,
             'thinking_format': 'interleaved',
             'supports_strict_tools': False,
             'supports_cache': False,
             'cache_type': 'ephemeral',
             'supports_session_affinity': False,
             'session_affinity_field': 'previous_response_id',
             'thinking_level_map': {},
             'supports_images': False,
             'supports_streaming_thinking': False,
             'requires_tool_choice': False,
             'reports_reasoning_tokens': False}},
 {'id': 'claude-3-5-haiku-20241022',
  'name': 'Claude 3.5 Haiku',
  'api': 'anthropic-messages',
  'provider': 'anthropic',
  'base_url': 'https://api.anthropic.com',
  'reasoning': False,
  'input': ['text', 'image'],
  'cost': {'input': 0.8, 'output': 4.0, 'cache_read': 0.0, 'cache_write': 0.0},
  'context_window': 200000,
  'max_tokens': 8192,
  'compat': {'developer_role': 'system',
             'supports_thinking': False,
             'thinking_format': 'interleaved',
             'supports_strict_tools': False,
             'supports_cache': False,
             'cache_type': 'ephemeral',
             'supports_session_affinity': False,
             'session_affinity_field': 'previous_response_id',
             'thinking_level_map': {},
             'supports_images': False,
             'supports_streaming_thinking': False,
             'requires_tool_choice': False,
             'reports_reasoning_tokens': False}},
 {'id': 'deepseek-v4-flash',
  'name': 'DeepSeek V4 Flash',
  'api': 'openai-chat-completions',
  'provider': 'deepseek',
  'base_url': 'https://api.deepseek.com',
  'reasoning': True,
  'input': ['text'],
  'cost': {'input': 0.14, 'output': 0.28, 'cache_read': 0.0028, 'cache_write': 0.0},
  'context_window': 1000000,
  'max_tokens': 393216,
  'compat': {'developer_role': 'system',
             'supports_thinking': False,
             'thinking_format': 'interleaved',
             'supports_strict_tools': False,
             'supports_cache': False,
             'cache_type': 'ephemeral',
             'supports_session_affinity': False,
             'session_affinity_field': 'previous_response_id',
             'thinking_level_map': {},
             'supports_images': False,
             'supports_streaming_thinking': False,
             'requires_tool_choice': False,
             'reports_reasoning_tokens': False}},
 {'id': 'deepseek-v4-pro',
  'name': 'DeepSeek V4 Pro',
  'api': 'openai-chat-completions',
  'provider': 'deepseek',
  'base_url': 'https://api.deepseek.com',
  'reasoning': True,
  'input': ['text'],
  'cost': {'input': 0.435, 'output': 0.87, 'cache_read': 0.003625, 'cache_write': 0.0},
  'context_window': 1000000,
  'max_tokens': 393216,
  'compat': {'developer_role': 'system',
             'supports_thinking': False,
             'thinking_format': 'interleaved',
             'supports_strict_tools': False,
             'supports_cache': False,
             'cache_type': 'ephemeral',
             'supports_session_affinity': False,
             'session_affinity_field': 'previous_response_id',
             'thinking_level_map': {},
             'supports_images': False,
             'supports_streaming_thinking': False,
             'requires_tool_choice': False,
             'reports_reasoning_tokens': False}}]]
